import Head from 'next/head'
import { GetServerSideProps, InferGetServerSidePropsType } from 'next'
import { IFeedback, ICard, ICategory } from 'src/shared/types'
import { GadgetCategoryCarousel } from 'src/widgets/gadget'
import { GadgetItemCarousel } from 'src/widgets/gadget'
import { FeedbackCarouselWidget } from 'src/widgets/feedback'
import { Box, ThemeOptions, useTheme } from '@mui/material'
import { WithContainer } from 'src/shared/ui'
import { api } from 'src/shared/api/axios-instance'


export default function Index({ cards, categories, feedbacks }: InferGetServerSidePropsType<typeof getServerSideProps>) {
  const theme: ThemeOptions = useTheme()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <WithContainer>
        <GadgetCategoryCarousel sx={{ my: theme.mY.large }} categories={categories} />
        <GadgetItemCarousel sx={{ my: theme.mY.large }} cards={cards} />
      </WithContainer>
      <Box sx={{ bgcolor: "darkGray", backgroundImage: "linear-gradient(rgba(255, 255, 255, 0.05), rgba(255, 255, 255, 0.05))", p: 6, my: theme.mY.large }}>
        <WithContainer>
          <FeedbackCarouselWidget feedbacks={feedbacks} />
        </WithContainer>
      </Box>
    </>
  )
}


export const getServerSideProps: GetServerSideProps<{ cards: ICard[], categories: ICategory[], feedbacks: IFeedback[] }> = async (context) => {

  const { data: cards } = await api.get<ICard[]>("/cards")

  const categories = [
    {
      id: 1,
      title: 'Phones',
      image:
        'https://new.axilthemes.com/demo/template/etrade/assets/images/product/categories/elec-4.png',
    },
    {
      id: 2,
      title: 'Computers',
      image:
        'https://new.axilthemes.com/demo/template/etrade/assets/images/product/categories/elec-5.png',

    },
    {
      id: 3,
      title: 'Accessories',
      image:
        'https://new.axilthemes.com/demo/template/etrade/assets/images/product/categories/elec-11.png',
    },
    {
      id: 4,
      title: 'Laptops',
      image:
        'https://new.axilthemes.com/demo/template/etrade/assets/images/product/categories/elec-6.png',
    },
    {
      id: 5,
      title: 'Monitors',
      image:
        'https://new.axilthemes.com/demo/template/etrade/assets/images/product/categories/elec-2.png',
    },
    {
      id: 6,
      title: 'Networking',
      image:
        'https://new.axilthemes.com/demo/template/etrade/assets/images/product/categories/elec-7.png',
    },
    {
      id: 7,
      title: 'PC Gaming',
      image:
        'https://new.axilthemes.com/demo/template/etrade/assets/images/product/categories/elec-8.png',
    },
    {
      id: 8,
      title: 'Watches',
      image:
        'https://new.axilthemes.com/demo/template/etrade/assets/images/product/categories/elec-1.png',
    },
    {
      id: 9,
      title: 'Headphones',
      image:
        'https://new.axilthemes.com/demo/template/etrade/assets/images/product/categories/elec-9.png',
    },
    {
      id: 10,
      title: 'Camera',
      image:
        'https://new.axilthemes.com/demo/template/etrade/assets/images/product/categories/elec-10.png',
    }
  ]

  const feedbacks = [
    {
      id: 1,
      content: "Your PC website is impressive! I love the clean design and user-friendly interface. It's easy to navigate and find the information I need.",
      date: "2023-02-15",
      nickname: "Bob",
      avatar: "https://new.axilthemes.com/demo/template/etrade/assets/images/testimonial/image-2.png"
    },
    {
      id: 2,
      content: "Your PC products are top-notch! I am very impressed with the quality of the components and the attention to detail in their design. Everything is working flawlessly and I am enjoying a fantastic computing experience.",
      date: "2023-02-15",
      nickname: "Ann",
      avatar: "https://new.axilthemes.com/demo/template/etrade/assets/images/testimonial/image-3.png"
    },
    {
      id: 3,
      content: "I am extremely happy with my purchase from your PC website. The product arrived quickly and was well-packaged, and it exceeded my expectations in terms of performance and reliability. I will definitely be recommending your products to others!",
      date: "2023-02-15",
      nickname: "Mr. Smith",
      avatar: "https://new.axilthemes.com/demo/template/etrade/assets/images/testimonial/image-1.png",
    },
    {
      id: 4,
      content: "I was blown away by the speed and power of your PC products. They are the best I have used, and I am very happy with my purchase. The build quality is excellent, and I would definitely recommend your products to anyone looking for a high-quality computing experience.",
      date: "2023-02-15",
      nickname: "Simpson"
    },
    {
      id: 5,
      content: "Your PC website is a gold mine of information for anyone looking to upgrade or build a new computer. The product descriptions are detailed and helpful, and the website is easy to navigate. I will definitely be returning to your website in the future!",
      date: "2023-02-15",
      nickname: "Mike"
    },
    {
      id: 6,
      content: "I am so glad I found your PC website. Your products are top-notch, and your customer service is excellent. I had a question about a product and the response was quick and helpful. I highly recommend your website to anyone looking for high-quality PC products.",
      date: "2023-02-15",
      nickname: "John"
    },
    {
      id: 7,
      content: "I have been using your PC products for a few months now, and I can say without hesitation that they are the best I have ever used. The performance is outstanding, and the build quality is excellent. I have recommended your products to several of my friends and colleagues, and they are all very happy with their purchases.",
      date: "2023-02-15",
      nickname: "Mary"
    },
    {
      id: 8,
      content: "Your PC website has everything I need to build my dream computer. The product selection is fantastic, and the prices are very reasonable. I appreciate the attention to detail in the product descriptions and the quality of the customer service. Thank you for providing such an excellent website!",
      date: "2023-02-15",
      nickname: "Jimmy"
    },
    {
      id: 9,
      content: "I recently purchased a PC product from your website and I am extremely satisfied with my purchase. The product arrived on time and was well-packaged, and it is working flawlessly. I will definitely be a repeat customer in the future!",
      date: "2023-02-15",
      nickname: "Goune"
    }
  ];


  return {
    props: { cards, categories, feedbacks }
  }
}
